# Generated by Django 4.2 on 2023-07-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "stakeholder",
            "0002_alter_stakeholder_address_alter_stakeholder_email_and_more",
        ),
        (
            "payments",
            "0004_alter_bank_created_at_alter_cashpayment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentaccount",
            unique_together={("name", "bank", "stakeholder")},
        ),
    ]
