# Generated by Django 4.2 on 2023-07-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0014_alter_invoice_created_at_and_more"),
        ("payments", "0005_alter_paymentaccount_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_payments",
                        to="invoice.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="chequepayment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="chequepayment",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="chequepayment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="invoicecashpayment",
            name="cash_payment",
        ),
        migrations.RemoveField(
            model_name="invoicecashpayment",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoicechequepayment",
            name="cheque_payment",
        ),
        migrations.RemoveField(
            model_name="invoicechequepayment",
            name="invoice",
        ),
        migrations.AddField(
            model_name="payment",
            name="additional_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional info"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("cheque", "Cheque")],
                default="cash",
                max_length=20,
                verbose_name="Payment type",
            ),
        ),
        migrations.DeleteModel(
            name="CashPayment",
        ),
        migrations.DeleteModel(
            name="ChequePayment",
        ),
        migrations.DeleteModel(
            name="InvoiceCashPayment",
        ),
        migrations.DeleteModel(
            name="InvoiceChequePayment",
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.payment",
                verbose_name="Payment Info",
            ),
        ),
    ]
