# Generated by Django 4.2 on 2023-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_invoicepayment_remove_chequepayment_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Amount"
            ),
        ),
    ]
