# Generated by Django 4.2 on 2023-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_done",
            field=models.BooleanField(
                default=False, verbose_name="Payment is concluded"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Turkish lira"),
                    ("USD", "US dollars"),
                    ("EUR", "Euro"),
                    ("GBP", "Pound sterling"),
                ],
                default="TRY",
                max_length=4,
                verbose_name="Currency",
            ),
        ),
    ]
