# Generated by Django 4.2 on 2023-08-30 11:38

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stakeholder",
            "0002_alter_stakeholder_address_alter_stakeholder_email_and_more",
        ),
        ("payments", "0009_paymentaccount_account_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicepayment",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.payment",
                verbose_name="Payment Info",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=payments.models.today,
                null=True,
                verbose_name="Due date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentaccount",
            unique_together={("name", "stakeholder")},
        ),
    ]
