# Generated by Django 4.2 on 2023-08-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribedWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_given_name", models.CharField(max_length=50)),
                (
                    "widget",
                    models.CharField(
                        choices=[
                            ("balance", "Balance"),
                            ("balance_graph", "Balange Graph"),
                            ("best_customers", "Best Customers"),
                            ("due_payments", "Due Payments"),
                            ("last_invoices", "Last Invoices"),
                            ("last_items", "Last Items"),
                            ("leftover_items", "Leftover Items"),
                            ("last_users", "Last Users"),
                        ],
                        max_length=100,
                        verbose_name="Widget",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
