# Generated by Django 4.2 on 2023-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribedwidget",
            name="user_given_name",
        ),
        migrations.AddField(
            model_name="subscribedwidget",
            name="user_settings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscribedwidget",
            name="widget_index",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscribedwidget",
            name="widget",
            field=models.CharField(
                choices=[
                    ("balance", "Balance"),
                    ("balance_graph", "Balange Graph"),
                    ("best_customers", "Best Customers"),
                    ("due_payments", "Due Payments"),
                    ("last_invoices", "Last Invoices"),
                    ("last_items", "Last Items"),
                    ("leftover_items", "Leftover Items"),
                    ("last_users", "Last Users"),
                ],
                max_length=100,
                verbose_name="Widget Name",
            ),
        ),
    ]
