# Generated by Django 4.2 on 2023-08-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_subscribedwidget_user_given_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribedwidget",
            old_name="widget",
            new_name="widget_name",
        ),
    ]
