# Generated by Django 4.1.5 on 2023-01-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseitemstock",
            name="amount",
        ),
    ]
