# Generated by Django 4.1.5 on 2023-01-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_warehouseitemstock_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="movement_type",
        ),
    ]
