# Generated by Django 4.1.5 on 2023-01-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("inventory", "0004_stockmovement_movement_type"),
        ("inventory", "0005_stockmovement_inventory_s_movemen_018f99_idx"),
        ("inventory", "0006_rename_inventory_s_movemen_018f99_idx_movement_type_index"),
        ("inventory", "0007_stockmovement_movement_type__in_query"),
        ("inventory", "0008_remove_stockmovement_movement_type_index_and_more"),
    ]

    dependencies = [
        ("inventory", "0003_remove_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("refund-purchase", "Refund Purchase"),
                    ("refund-sale", "Refund Sale"),
                ],
                default="purchase",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_s_movemen_018f99_idx"
            ),
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="movement_type_index",
            old_name="inventory_s_movemen_018f99_idx",
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                models.Q(("movement_type__in", ("purchase", "refund-sale"))),
                models.Q(("movement_type__in", ("sale", "refund-purchase"))),
                name="movement_type__in_query",
            ),
        ),
        migrations.RemoveIndex(
            model_name="stockmovement",
            name="movement_type_index",
        ),
        migrations.RemoveIndex(
            model_name="stockmovement",
            name="movement_type__in_query",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="movement_type",
        ),
    ]
