# Generated by Django 4.1.5 on 2023-01-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_stockmovement_movement_type_squashed_0008_remove_stockmovement_movement_type_index_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitem",
            name="inactivated",
            field=models.BooleanField(default=False, verbose_name="Gizli"),
        ),
        migrations.AddField(
            model_name="item",
            name="inactivated",
            field=models.BooleanField(default=False, verbose_name="Gizli"),
        ),
    ]
