# Generated by Django 4.1.5 on 2023-02-16 10:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_historicalitem_inactivated_item_inactivated"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="warehouseitemstock",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=19, verbose_name="Miktar"
            ),
        ),
    ]
