# Generated by Django 4.1.5 on 2023-02-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_item_managers_warehouseitemstock_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouseitemstock",
            old_name="amount",
            new_name="amount_db",
        ),
    ]
