# Generated by Django 4.1.5 on 2023-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_rename_amount_warehouseitemstock_amount_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitemstock",
            name="amount_db",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                max_digits=19,
                null=True,
                verbose_name="Miktar",
            ),
        ),
    ]
