# Generated by Django 4.1.5 on 2023-04-19 23:52

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_warehouseitemstock_amount_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="db.inventory.tax.name"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name="Barkod",
            ),
        ),
        migrations.AlterField(
            model_name="historicalitem",
            name="thumbnail",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="Barkod"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=inventory.models.get_item_image_location,
                verbose_name="thumbnail",
            ),
        ),
    ]
