# Generated by Django 4.2 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_remove_warehouse_mobile_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="inactivated",
            field=models.BooleanField(default=False, verbose_name="Inactivated"),
        ),
        migrations.AlterField(
            model_name="item",
            name="inactivated",
            field=models.BooleanField(default=False, verbose_name="Inactivated"),
        ),
    ]
