# Generated by Django 4.2 on 2023-07-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_historicalitem_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
    ]
