# Generated by Django 4.1.5 on 2023-01-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Satıcı", "Supplier"),
                            ("Müşteri", "Customer"),
                            ("Müşteri ve Satıcı", "Customer And Supplier"),
                        ],
                        max_length=30,
                        verbose_name="Rolü",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Tam Adı")),
                (
                    "shortname",
                    models.CharField(max_length=100, verbose_name="Kısa/Takma Adı"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="E-Posta"
                    ),
                ),
                (
                    "vkntckn",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="VKN/TCKN"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Adres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StakeholderEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pozisyonu"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Adı")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="E-Posta"
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="stakeholder.stakeholder",
                        verbose_name="temsil ettiği kurum ya da kişi",
                    ),
                ),
            ],
        ),
    ]
