# Generated by Django 4.2 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="address",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="name",
            field=models.CharField(max_length=400, verbose_name="Full name"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="role",
            field=models.CharField(
                choices=[
                    ("Satıcı", "Supplier"),
                    ("Müşteri", "Customer"),
                    ("Müşteri ve Satıcı", "Customer And Supplier"),
                ],
                max_length=30,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="shortname",
            field=models.CharField(max_length=100, verbose_name="Short name"),
        ),
    ]
