# Generated by Django 4.1.5 on 2023-01-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stakeholder", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturma Tarihi",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Değiştirme Tarihi"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("refund-purchase", "Refund Purchase"),
                            ("refund-sale", "Refund Sale"),
                        ],
                        max_length=20,
                        verbose_name="Fatura Tipi",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Fatura Adı")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "invoice_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fatura Koşulları"
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        default=invoice.models.week_from_now,
                        verbose_name="Son Ödeme Tarihi",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "US Dollars"),
                            ("EUR", "Euro"),
                            ("GBP", "Pound sterling"),
                        ],
                        default="TRY",
                        max_length=4,
                        verbose_name="Fatura Para Birimi",
                    ),
                ),
                (
                    "currency_exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        verbose_name="Döviz Kuru",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        verbose_name="Toplam Kdv Hariç Tutar",
                    ),
                ),
                (
                    "total_with_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        verbose_name="Toplam Kdv Dahil Tutar",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "related_invoice",
                    models.ManyToManyField(
                        blank=True,
                        related_name="refund_invoice",
                        to="invoice.invoice",
                        verbose_name="Alakalı Fatura(lar)",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stakeholder.stakeholder",
                        verbose_name="Alakalı Taraf",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değiştiren",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="inventory.warehouse",
                        verbose_name="Alakalı Depo",
                    ),
                ),
            ],
            options={
                "permissions": [("view_all_invoices", "Tüm faturaları görebilir")],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Fiyat"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoice.invoice",
                        verbose_name="Alakalı Fatura",
                    ),
                ),
                (
                    "stock_movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_item",
                        to="inventory.stockmovement",
                        verbose_name="Stok Hareketi",
                    ),
                ),
            ],
        ),
    ]
