# Generated by Django 4.1.5 on 2023-01-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_historicalitem_inactivated_item_inactivated"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="stock_movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_item",
                to="inventory.stockmovement",
                verbose_name="Stok Hareketi",
            ),
        ),
    ]
