# Generated by Django 4.1.5 on 2023-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_alter_invoice_options_alter_invoice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecondition",
            name="condition_name",
            field=models.CharField(
                default="",
                max_length=100,
                verbose_name="Condition identifier name(ex: Default conditions)",
            ),
            preserve_default=False,
        ),
    ]
