# Generated by Django 4.1.5 on 2023-04-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_invoicecondition_condition_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_conditions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoice.invoicecondition",
                verbose_name="Invoice Conditions",
            ),
        ),
    ]
