# Generated by Django 4.1.5 on 2023-04-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_alter_invoice_invoice_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecondition",
            name="hidden",
            field=models.BooleanField(
                default=False,
                verbose_name="Hide from list view(will persist in invoices that uses this)",
            ),
        ),
    ]
