# Generated by Django 4.1.5 on 2023-05-01 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_invoicecondition_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicecondition",
            name="condition_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Condition identifier name(ex: Default conditions)",
            ),
        ),
        migrations.AlterField(
            model_name="invoicecondition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
