# Generated by Django 4.2 on 2023-07-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_alter_invoice_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceconditiontemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
    ]
